# -*- coding: utf-8 -*-
"""Satellite Cloud.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1evuyzZb4Elf9dwj6JendE6FEiAnfjySZ
"""

import numpy as np
import pandas as pd

R_EARTH_KM = 6371.0

def build_angular_grid(delta_lat_deg=5.0, delta_lon_deg=5.0):
    # Edges
    lat_edges = np.arange(-90.0, 90.0 + delta_lat_deg, delta_lat_deg)
    lon_edges = np.arange(-180.0, 180.0 + delta_lon_deg, delta_lon_deg)

    n_lat = len(lat_edges) - 1
    n_lon = len(lon_edges) - 1

    rows = []
    grid_id = 0

    for i in range(n_lat):
        lat0, lat1 = lat_edges[i], lat_edges[i + 1]
        latc = 0.5 * (lat0 + lat1)

        # exact spherical area for this lat band + lon span
        lat0r = np.deg2rad(lat0)
        lat1r = np.deg2rad(lat1)

        for j in range(n_lon):
            lon0, lon1 = lon_edges[j], lon_edges[j + 1]
            lonc = 0.5 * (lon0 + lon1)

            dlon = np.deg2rad(lon1 - lon0)
            area_km2 = (R_EARTH_KM ** 2) * dlon * (np.sin(lat1r) - np.sin(lat0r))

            rows.append({
                "grid_id": grid_id,
                "i_lat": i,
                "j_lon": j,
                "lat_min": lat0,
                "lat_max": lat1,
                "lon_min": lon0,
                "lon_max": lon1,
                "lat_c": latc,
                "lon_c": lonc,
                "area_km2": float(area_km2),
            })
            grid_id += 1

    grids = pd.DataFrame(rows)

    meta = {
        "delta_lat_deg": delta_lat_deg,
        "delta_lon_deg": delta_lon_deg,
        "n_lat": n_lat,
        "n_lon": n_lon,
        "n_cells": int(n_lat * n_lon),
        "lat_edges": lat_edges,
        "lon_edges": lon_edges,
    }
    return grids, meta


def wrap_lon(lon):
    # wrap to [-180, 180)
    return ((lon + 180.0) % 360.0) - 180.0

def latlon_to_grid_id(lat, lon, meta):
    """
    Map a (lat, lon) to grid_id using meta from build_angular_grid.
    lat in [-90,90], lon any real.
    """
    lat = np.clip(lat, -90.0 + 1e-12, 90.0 - 1e-12)
    lon = wrap_lon(lon)

    lat_edges = meta["lat_edges"]
    lon_edges = meta["lon_edges"]
    n_lon = meta["n_lon"]

    i = np.searchsorted(lat_edges, lat, side="right") - 1
    j = np.searchsorted(lon_edges, lon, side="right") - 1

    # safety clamp
    i = int(np.clip(i, 0, meta["n_lat"] - 1))
    j = int(np.clip(j, 0, meta["n_lon"] - 1))

    return i * n_lon + j


if __name__ == "__main__":
    grids, meta = build_angular_grid(5.0, 5.0)
    print(grids.head())
    print("N cells:", meta["n_cells"])

    # quick test
    print("LA-ish grid:", latlon_to_grid_id(34.0, -118.25, meta))

import numpy as np
import matplotlib.pyplot as plt

def latlon_to_xyz(lat_deg, lon_deg, R=1.0):
    lat = np.deg2rad(lat_deg)
    lon = np.deg2rad(lon_deg)
    x = R * np.cos(lat) * np.cos(lon)
    y = R * np.cos(lat) * np.sin(lon)
    z = R * np.sin(lat)
    return x, y, z

def plot_grid_centers_globe(grids):
    xs, ys, zs = latlon_to_xyz(grids["lat_c"].values, grids["lon_c"].values, R=1.0)

    fig = plt.figure(figsize=(7, 7))
    ax = fig.add_subplot(111, projection="3d")

    # draw a faint sphere for reference
    u = np.linspace(0, 2*np.pi, 60)
    v = np.linspace(0, np.pi, 30)
    X = np.outer(np.cos(u), np.sin(v))
    Y = np.outer(np.sin(u), np.sin(v))
    Z = np.outer(np.ones_like(u), np.cos(v))
    ax.plot_surface(X, Y, Z, alpha=0.08, linewidth=0)

    ax.scatter(xs, ys, zs, s=4, alpha=0.8)

    ax.set_title("Grid centers on a globe")
    ax.set_axis_off()
    ax.view_init(elev=20, azim=30)
    plt.show()

# usage:
plot_grid_centers_globe(grids)

pip install cartopy

import matplotlib.pyplot as plt
import cartopy.crs as ccrs
import cartopy.feature as cfeature

def plot_world_with_grid(meta, line_w=0.6):
    lat_edges = meta["lat_edges"]
    lon_edges = meta["lon_edges"]

    fig = plt.figure(figsize=(14, 7))
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.set_global()

    # Background: ocean + land + coastlines (simple)
    ax.add_feature(cfeature.OCEAN, alpha=0.35)
    ax.add_feature(cfeature.LAND, alpha=0.6)
    ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

    # Draw your grid lines
    for lon in lon_edges:
        ax.plot([lon, lon], [-90, 90], transform=ccrs.PlateCarree(), linewidth=line_w)
    for lat in lat_edges:
        ax.plot([-180, 180], [lat, lat], transform=ccrs.PlateCarree(), linewidth=line_w)

    ax.set_title(f"Earth (2D) + Angular Grid (Δlat={meta['delta_lat_deg']}°, Δlon={meta['delta_lon_deg']}°)")
    plt.show()

# usage:
grids, meta = build_angular_grid(5.0, 5.0)
plot_world_with_grid(meta)

pip install rasterio

import numpy as np
import rasterio

def add_population_from_geotiff(grids, meta, tif_path, band=1, assume_counts=True):
    """
    Adds columns:
      - population: sum of people in the grid cell
      - pop_share: population / global population

    Works best when tif values are "people per pixel" (counts).
    """
    dlat = meta["delta_lat_deg"]
    dlon = meta["delta_lon_deg"]
    n_lat = meta["n_lat"]
    n_lon = meta["n_lon"]
    n_cells = meta["n_cells"]

    pop = np.zeros(n_cells, dtype=np.float64)

    with rasterio.open(tif_path) as src:
        # Basic sanity checks
        if src.count < band:
            raise ValueError(f"Raster has {src.count} bands, but band={band} was requested.")

        if src.crs is None:
            raise ValueError("Raster CRS is missing. Need a WGS84 (EPSG:4326) raster.")
        # Many pop rasters are EPSG:4326; if not, reproject first (we can do that in the next step).
        # (Keeping this simple for now.)

        t = src.transform
        nodata = src.nodata

        # Iterate over raster blocks/windows (memory-safe)
        for _, window in src.block_windows(band):
            arr = src.read(band, window=window)

            # Mask invalid
            m = np.isfinite(arr)
            if nodata is not None:
                m &= (arr != nodata)
            if assume_counts:
                m &= (arr > 0)

            if not np.any(m):
                continue

            # Build lon/lat arrays for pixel centers in this window (vectorized affine math)
            # col indices: [col_off .. col_off+width-1], row indices similarly
            cols = (np.arange(window.col_off, window.col_off + window.width) + 0.5)
            rows = (np.arange(window.row_off, window.row_off + window.height) + 0.5)
            cc, rr = np.meshgrid(cols, rows)

            # Affine transform: x = c + a*col + b*row ; y = f + d*col + e*row
            lon = t.c + t.a * cc + t.b * rr
            lat = t.f + t.d * cc + t.e * rr

            vals = arr[m].astype(np.float64)
            latv = lat[m]
            lonv = lon[m]

            # Wrap/clip to stable ranges
            latv = np.clip(latv, -90.0 + 1e-12, 90.0 - 1e-12)
            lonv = ((lonv + 180.0) % 360.0) - 180.0

            # Map to your angular grid indices
            i = np.floor((latv + 90.0) / dlat).astype(np.int64)
            j = np.floor((lonv + 180.0) / dlon).astype(np.int64)
            i = np.clip(i, 0, n_lat - 1)
            j = np.clip(j, 0, n_lon - 1)

            gid = i * n_lon + j

            # Accumulate population into grid cells
            np.add.at(pop, gid, vals)

    grids2 = grids.copy()
    grids2["population"] = pop
    total = pop.sum()
    grids2["pop_share"] = grids2["population"] / total if total > 0 else 0.0
    return grids2

from google.colab import drive
drive.mount('/content/drive')

!mkdir -p "/content/drive/MyDrive/sat_sim_project"
!wget -O "/content/drive/MyDrive/sat_sim_project/worldpop_ppp_2020_1km.tif" \
"https://data.worldpop.org/GIS/Population/Global_2000_2020/2020/0_Mosaicked/ppp_2020_1km_Aggregated.tif"

!ls -lh "/content/drive/MyDrive/sat_sim_project/worldpop_ppp_2020_1km.tif"

import os

pop_tif = "/content/drive/MyDrive/sat_sim_project/worldpop_ppp_2020_1km.tif"
assert os.path.exists(pop_tif), f"Not found: {pop_tif}"

grids = add_population_from_geotiff(grids, meta, pop_tif)

print(grids[["grid_id","lat_c","lon_c","population","pop_share"]].head())
print("Total population from raster:", grids["population"].sum())

import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(14,6))
plt.scatter(grids["lon_c"], grids["lat_c"], c=np.log10(grids["population"]+1), s=8)
plt.xlim(-180,180); plt.ylim(-90,90)
plt.xlabel("Longitude"); plt.ylabel("Latitude")
plt.title("Population per grid cell (log10(pop+1))")
plt.colorbar(label="log10(pop+1)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt

# --- constants ---
MU_EARTH = 398600.4418  # km^3 / s^2
R_EARTH = 6378.137      # km (WGS84 equatorial radius-ish)
OMEGA_EARTH = 7.2921150e-5  # rad/s

def R1(a):
    ca, sa = np.cos(a), np.sin(a)
    return np.array([[1,0,0],[0,ca,-sa],[0,sa,ca]])

def R3(a):
    ca, sa = np.cos(a), np.sin(a)
    return np.array([[ca,-sa,0],[sa, ca,0],[0,  0,1]])

def make_walker_shell(P=72, S=22, inc_deg=53.0, h_km=550.0, F=1):
    inc = np.deg2rad(inc_deg)
    a = R_EARTH + h_km
    n = np.sqrt(MU_EARTH / a**3)  # rad/s

    sats = []
    sat_id = 0
    for p in range(P):
        raan = 2*np.pi * p / P
        for s in range(S):
            M0 = 2*np.pi * (s / S) + 2*np.pi * (F * p) / (P * S)
            sats.append((sat_id, p, s, raan, inc, a, n, M0))
            sat_id += 1

    return {"P": P, "S": S, "N": P*S, "inc": inc, "a": a, "n": n, "sats": sats}

def sat_positions_ecef(shell, t_sec):
    a = shell["a"]
    positions = np.zeros((shell["N"], 3), dtype=np.float64)

    theta = OMEGA_EARTH * t_sec
    R_eci2ecef = R3(theta)

    for (sid, p, s, raan, inc, a, n, M0) in shell["sats"]:
        nu = (M0 + n * t_sec) % (2*np.pi)
        r_pqw = np.array([a*np.cos(nu), a*np.sin(nu), 0.0])

        r_eci = (R3(raan) @ (R1(inc) @ r_pqw))
        r_ecef = R_eci2ecef @ r_eci
        positions[sid] = r_ecef

    return positions

def ecef_to_latlon(r_ecef):
    x, y, z = r_ecef[:,0], r_ecef[:,1], r_ecef[:,2]
    lon = np.arctan2(y, x)
    hyp = np.sqrt(x*x + y*y)
    lat = np.arctan2(z, hyp)

    lat_deg = np.rad2deg(lat)
    lon_deg = np.rad2deg(lon)

    # optional: wrap to [-180, 180)
    lon_deg = (lon_deg + 180) % 360 - 180
    return lat_deg, lon_deg

def plot_sats_2d_cartopy(lat_deg, lon_deg, title="Sub-satellite points (2D)"):
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature

    fig = plt.figure(figsize=(14,7))
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.set_global()

    ax.add_feature(cfeature.OCEAN, alpha=0.35)
    ax.add_feature(cfeature.LAND, alpha=0.6)
    ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

    ax.scatter(lon_deg, lat_deg, s=4, transform=ccrs.PlateCarree(), alpha=0.8)
    ax.set_title(title)
    plt.show()

# ---- run ----
shell = make_walker_shell(P=72, S=22, inc_deg=53.0, h_km=550.0, F=1)

r0 = sat_positions_ecef(shell, t_sec=0)  # <-- this was missing
lat0, lon0 = ecef_to_latlon(r0)

plot_sats_2d_cartopy(lat0, lon0, title="Sub-satellite points @ t=0s")

# 2D ground tracks: show exactly num_planes planes
def plot_ground_tracks(shell, num_planes=10, sats_per_plane=2, step_sec=60):
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature
    import numpy as np
    import matplotlib.pyplot as plt

    def sat_pos_ecef_single(sat_tuple, t_sec):
        (sid, p, s, raan, inc, a, n_mean, M0) = sat_tuple
        nu = (M0 + n_mean * t_sec) % (2*np.pi)
        r_pqw = np.array([a*np.cos(nu), a*np.sin(nu), 0.0])
        r_eci = (R3(raan) @ (R1(inc) @ r_pqw))
        theta = OMEGA_EARTH * t_sec
        return R3(theta) @ r_eci

    def latlon_from_vec(r):
        x, y, z = r[0], r[1], r[2]
        lon = np.arctan2(y, x)
        hyp = np.sqrt(x*x + y*y)
        lat = np.arctan2(z, hyp)
        lon_deg = (np.rad2deg(lon) + 180) % 360 - 180
        lat_deg = np.rad2deg(lat)
        return lat_deg, lon_deg

    def split_on_dateline(lat, lon):
        lat = np.asarray(lat); lon = np.asarray(lon)
        jumps = np.where(np.abs(np.diff(lon)) > 180)[0]
        start = 0
        segs = []
        for j in jumps:
            segs.append((lat[start:j+1], lon[start:j+1]))
            start = j+1
        segs.append((lat[start:], lon[start:]))
        return segs

    # one orbit period
    T_orbit = 2*np.pi / shell["n"]
    times = np.arange(0, T_orbit + 1e-9, step_sec)

    fig = plt.figure(figsize=(14, 7))
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.set_global()
    ax.add_feature(cfeature.OCEAN, alpha=0.35)
    ax.add_feature(cfeature.LAND, alpha=0.6)
    ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

    P, S = shell["P"], shell["S"]

    # choose exactly num_planes plane indices spread across [0, P-1]
    plane_ids = np.linspace(0, P-1, num_planes, dtype=int)

    for p in plane_ids:
        for k in range(sats_per_plane):
            s_idx = (k * max(1, S // sats_per_plane)) % S
            sid = p * S + s_idx
            sat_tuple = shell["sats"][sid]

            lat_list, lon_list = [], []
            for t in times:
                r = sat_pos_ecef_single(sat_tuple, t)
                lat, lon = latlon_from_vec(r)
                lat_list.append(lat); lon_list.append(lon)

            for lat_seg, lon_seg in split_on_dateline(lat_list, lon_list):
                ax.plot(lon_seg, lat_seg, transform=ccrs.PlateCarree(), linewidth=1)

    ax.set_title(f"Ground tracks over one orbit (num_planes={num_planes})")
    plt.show()

# --- run with num_planes = 10 ---
plot_ground_tracks(shell, num_planes=72, sats_per_plane=1, step_sec=60)

import matplotlib.pyplot as plt

def plot_sats_2d_cartopy(lat_deg, lon_deg, title="Sub-satellite points (2D)"):
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature

    fig = plt.figure(figsize=(14,7))
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.set_global()

    ax.add_feature(cfeature.OCEAN, alpha=0.35)
    ax.add_feature(cfeature.LAND, alpha=0.6)
    ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

    ax.scatter(lon_deg, lat_deg, s=4, transform=ccrs.PlateCarree(), alpha=0.8)
    ax.set_title(title)
    plt.show()

lat0, lon0 = ecef_to_latlon(r0)
plot_sats_2d_cartopy(lat0, lon0, title="Sub-satellite points @ t=0s")

import numpy as np

def plot_sats_over_n_orbits(shell, n_orbits=1, step_sec=1200, title=None):
    """
    Scatter sub-satellite points for ALL satellites over n_orbits.
    step_sec controls how often we sample positions (bigger = faster/less dense).
    """
    # One orbital period (seconds)
    T_orbit = 2*np.pi / shell["n"]

    times = np.arange(0, n_orbits * T_orbit + 1e-9, step_sec)

    lat_all = []
    lon_all = []

    for t in times:
        r = sat_positions_ecef(shell, t)      # (N,3) ECEF km
        lat, lon = ecef_to_latlon(r)          # (N,), (N,)
        lat_all.append(lat)
        lon_all.append(lon)

    lat_all = np.concatenate(lat_all)
    lon_all = np.concatenate(lon_all)

    if title is None:
        title = f"Sub-satellite points over {n_orbits} orbits (dt={step_sec}s)"

    plot_sats_2d_cartopy(lat_all, lon_all, title=title)
plot_sats_over_n_orbits(shell, n_orbits=10, step_sec=180)

import numpy as np
import matplotlib.pyplot as plt

def sat_slider(shell, n_orbits=2, step_sec=300, figsize=(14,7)):
    # Orbital period (seconds)
    T_orbit = 2*np.pi / shell["n"]
    times = np.arange(0, n_orbits * T_orbit + 1e-9, step_sec)

    import cartopy.crs as ccrs
    import cartopy.feature as cfeature
    from ipywidgets import interact, IntSlider

    def _plot(idx):
        t = float(times[idx])
        r = sat_positions_ecef(shell, t)
        lat, lon = ecef_to_latlon(r)

        fig = plt.figure(figsize=figsize)
        ax = plt.axes(projection=ccrs.PlateCarree())
        ax.set_global()

        ax.add_feature(cfeature.OCEAN, alpha=0.35)
        ax.add_feature(cfeature.LAND, alpha=0.6)
        ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

        ax.scatter(lon, lat, s=6, transform=ccrs.PlateCarree(), alpha=0.85)
        ax.set_title(f"Satellite positions @ t={t:.0f}s  (orbit={t/T_orbit:.2f})")
        plt.show()

    interact(_plot, idx=IntSlider(min=0, max=len(times)-1, step=1, value=0))

sat_slider(shell, n_orbits=2, step_sec=300)

import numpy as np
import matplotlib.pyplot as plt

def show_sat_snapshots(shell, n_orbits=1, step_sec=300, figsize=(14,7)):
    # Orbital period (seconds)
    T_orbit = 2*np.pi / shell["n"]
    times = np.arange(0, n_orbits * T_orbit + 1e-9, step_sec)

    import cartopy.crs as ccrs
    import cartopy.feature as cfeature

    for t in times:
        r = sat_positions_ecef(shell, t)   # (N,3) ECEF km
        lat, lon = ecef_to_latlon(r)       # (N,), (N,)

        fig = plt.figure(figsize=figsize)
        ax = plt.axes(projection=ccrs.PlateCarree())
        ax.set_global()

        ax.add_feature(cfeature.OCEAN, alpha=0.35)
        ax.add_feature(cfeature.LAND, alpha=0.6)
        ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

        ax.scatter(lon, lat, s=6, transform=ccrs.PlateCarree(), alpha=0.85)

        orbit_frac = t / T_orbit
        ax.set_title(f"Satellite positions @ t={t:.0f}s  (orbit={orbit_frac:.2f})")
        plt.show()
        plt.close(fig)

show_sat_snapshots(shell, n_orbits=10, step_sec=300)

import numpy as np
import matplotlib.pyplot as plt

def show_sat_snapshots_one_plane(shell, plane_idx=0, n_orbits=2, step_sec=300, figsize=(14,7)):
    # Orbital period (seconds)
    T_orbit = 2*np.pi / shell["n"]
    times = np.arange(0, n_orbits * T_orbit + 1e-9, step_sec)

    # Satellite IDs that belong to this plane
    plane_sids = [sid for (sid, p, s, raan, inc, a, n, M0) in shell["sats"] if p == plane_idx]
    print(f"Plane {plane_idx}: {len(plane_sids)} satellites per frame")

    import cartopy.crs as ccrs
    import cartopy.feature as cfeature

    for t in times:
        r_all = sat_positions_ecef(shell, t)      # (N,3)
        r = r_all[plane_sids, :]                  # (S,3) only this plane
        lat, lon = ecef_to_latlon(r)

        fig = plt.figure(figsize=figsize)
        ax = plt.axes(projection=ccrs.PlateCarree())
        ax.set_global()
        ax.add_feature(cfeature.OCEAN, alpha=0.35)
        ax.add_feature(cfeature.LAND, alpha=0.6)
        ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

        ax.scatter(lon, lat, s=10, transform=ccrs.PlateCarree(), alpha=0.9)
        ax.set_title(f"Plane {plane_idx} satellites @ t={t:.0f}s  (orbit={t/T_orbit:.2f})")

        plt.show()
        plt.close(fig)

# Example: show only plane 0
show_sat_snapshots_one_plane(shell, plane_idx=0, n_orbits=2, step_sec=300)

import numpy as np
import matplotlib.pyplot as plt

def make_plane_gif(shell, plane_idx=0, n_orbits=5, step_sec=300, fps=8,
                   gif_path="plane_motion.gif", figsize=(14,7)):
    import imageio.v2 as imageio
    from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature

    # Orbital period (seconds)
    T_orbit = 2*np.pi / shell["n"]
    times = np.arange(0, n_orbits * T_orbit + 1e-9, step_sec)

    # indices of sats in the chosen plane
    plane_sids = [sid for (sid, p, s, raan, inc, a, n, M0) in shell["sats"] if p == plane_idx]
    print(f"Plane {plane_idx}: {len(plane_sids)} satellites per frame, {len(times)} frames total")

    frames = []
    for t in times:
        r_all = sat_positions_ecef(shell, t)  # (N,3)
        r = r_all[plane_sids, :]              # (S,3)
        lat, lon = ecef_to_latlon(r)

        fig = plt.figure(figsize=figsize)
        canvas = FigureCanvas(fig)            # attaches agg canvas to fig
        ax = plt.axes(projection=ccrs.PlateCarree())
        ax.set_global()

        ax.add_feature(cfeature.OCEAN, alpha=0.35)
        ax.add_feature(cfeature.LAND, alpha=0.6)
        ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

        ax.scatter(lon, lat, s=12, transform=ccrs.PlateCarree(), alpha=0.9)
        ax.set_title(f"Plane {plane_idx} @ t={t:.0f}s (orbit={t/T_orbit:.2f})")

        # Render and grab RGBA buffer
        canvas.draw()
        w, h = canvas.get_width_height()
        rgba = np.asarray(canvas.buffer_rgba()).reshape(h, w, 4)
        rgb = rgba[:, :, :3].copy()  # drop alpha

        frames.append(rgb)
        plt.close(fig)

    imageio.mimsave(gif_path, frames, fps=fps)
    print(f"GIF saved to: {gif_path}")

    # Optional: show inline (works in most notebooks)
    try:
        from IPython.display import Image, display
        display(Image(filename=gif_path))
    except Exception:
        pass

# If you don't have imageio yet:
# !pip -q install imageio

make_plane_gif(shell, plane_idx=17, n_orbits=10, step_sec=300, fps=8, gif_path="plane0_2orbits.gif")

import numpy as np
import matplotlib.pyplot as plt

def build_plane_index(shell):
    """
    Returns: dict plane -> list of sids in that plane ordered by s index.
    shell["sats"] items look like: (sid, p, s, raan, inc, a, n, M0)
    """
    by_plane = {}
    for (sid, p, s, raan, inc, a, n, M0) in shell["sats"]:
        by_plane.setdefault(p, []).append((s, sid))
    # sort by satellite index s within each plane
    for p in by_plane:
        by_plane[p].sort(key=lambda x: x[0])
        by_plane[p] = [sid for (s, sid) in by_plane[p]]
    return by_plane

def build_links_one_timestep(shell, t_sec, inter_mode="one_per_neighbor"):
    """
    inter_mode:
      - "one_per_neighbor": connect to the closest sat in plane p-1 and also in p+1 (2 links max)
      - "one_total": connect to the closest sat among BOTH neighboring planes (1 link max)
    Returns a list of undirected edges (i,j) with i<j.
    """
    sats = shell["sats"]
    N = len(sats)
    P = shell["P"]
    by_plane = build_plane_index(shell)

    # positions in ECEF (km)
    r_all = sat_positions_ecef(shell, t_sec)  # (N,3)

    edges = set()

    # --- Intra-plane: front & behind (ring)
    for p, sids in by_plane.items():
        S = len(sids)
        for idx, sid in enumerate(sids):
            sid_prev = sids[(idx - 1) % S]
            sid_next = sids[(idx + 1) % S]
            a, b = sorted((sid, sid_prev))
            edges.add((a, b))
            a, b = sorted((sid, sid_next))
            edges.add((a, b))

    # --- Inter-plane: closest in neighboring plane(s)
    for (sid, p, s, raan, inc, a, n, M0) in sats:
        neigh_planes = [ (p - 1) % P, (p + 1) % P ]
        candidates = []
        for pn in neigh_planes:
            for sid2 in by_plane[pn]:
                d = np.linalg.norm(r_all[sid] - r_all[sid2])
                candidates.append((d, pn, sid2))

        if not candidates:
            continue

        if inter_mode == "one_total":
            d, pn, best = min(candidates, key=lambda x: x[0])
            a, b = sorted((sid, best))
            edges.add((a, b))
        else:  # "one_per_neighbor"
            for pn in neigh_planes:
                cand_pn = [x for x in candidates if x[1] == pn]
                if cand_pn:
                    d, _, best = min(cand_pn, key=lambda x: x[0])
                    a, b = sorted((sid, best))
                    edges.add((a, b))

    return sorted(edges)

def _plot_wrapped_geodesic(ax, lon1, lat1, lon2, lat2, transform, max_jump=180):
    """
    Helps avoid ugly lines across the dateline by skipping huge lon jumps.
    Simple and robust: if it jumps too much, don't draw that edge.
    """
    if abs(lon1 - lon2) > max_jump:
        return
    ax.plot([lon1, lon2], [lat1, lat2], transform=transform, linewidth=0.6, alpha=0.35)

def plot_sats_and_links(shell, t_sec=0, inter_mode="one_per_neighbor", figsize=(14,7)):
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature

    # compute positions
    r_all = sat_positions_ecef(shell, t_sec)
    lat, lon = ecef_to_latlon(r_all)

    # build edges
    edges = build_links_one_timestep(shell, t_sec, inter_mode=inter_mode)
    print(f"N satellites: {len(shell['sats'])} | edges drawn: {len(edges)} | t={t_sec}s")

    # plot
    fig = plt.figure(figsize=figsize)
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.set_global()

    ax.add_feature(cfeature.OCEAN, alpha=0.35)
    ax.add_feature(cfeature.LAND, alpha=0.6)
    ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

    # links (use Geodetic for nicer great-circle-ish lines)
    for i, j in edges:
        _plot_wrapped_geodesic(
            ax,
            float(lon[i]), float(lat[i]),
            float(lon[j]), float(lat[j]),
            transform=ccrs.Geodetic()
        )

    # satellites
    ax.scatter(lon, lat, s=6, transform=ccrs.PlateCarree(), alpha=0.9)

    T_orbit = 2*np.pi / shell["n"]
    ax.set_title(f"Satellites + links @ t={t_sec:.0f}s (orbit={t_sec/T_orbit:.2f}) | inter={inter_mode}")
    plt.show()


# Example: one timestep (t=0)
plot_sats_and_links(shell, t_sec=0, inter_mode="one_per_neighbor")
# or: plot_sats_and_links(shell, t_sec=0, inter_mode="one_total")

import numpy as np
import matplotlib.pyplot as plt

def build_plane_index(shell):
    by_plane = {}
    for (sid, p, s, raan, inc, a, n, M0) in shell["sats"]:
        by_plane.setdefault(p, []).append((s, sid))
    for p in by_plane:
        by_plane[p].sort(key=lambda x: x[0])
        by_plane[p] = [sid for (s, sid) in by_plane[p]]
    return by_plane

def build_links_one_timestep(shell, t_sec, inter_mode="one_per_neighbor"):
    """
    inter_mode:
      - "one_per_neighbor": closest in plane p-1 AND closest in plane p+1
      - "one_total": closest among both neighbor planes (one link)
    """
    sats = shell["sats"]
    P = shell["P"]
    by_plane = build_plane_index(shell)

    r_all = sat_positions_ecef(shell, t_sec)  # (N,3) ECEF km
    edges = set()

    # Intra-plane ring: front & behind
    for p, sids in by_plane.items():
        S = len(sids)
        for idx, sid in enumerate(sids):
            sid_prev = sids[(idx - 1) % S]
            sid_next = sids[(idx + 1) % S]
            edges.add(tuple(sorted((sid, sid_prev))))
            edges.add(tuple(sorted((sid, sid_next))))

    # Inter-plane: closest in neighboring plane(s)
    for (sid, p, s, raan, inc, a, n, M0) in sats:
        neigh_planes = [ (p - 1) % P, (p + 1) % P ]

        if inter_mode == "one_total":
            best = None
            best_d = float("inf")
            for pn in neigh_planes:
                for sid2 in by_plane[pn]:
                    d = np.linalg.norm(r_all[sid] - r_all[sid2])
                    if d < best_d:
                        best_d = d
                        best = sid2
            if best is not None:
                edges.add(tuple(sorted((sid, best))))
        else:  # one_per_neighbor
            for pn in neigh_planes:
                best = None
                best_d = float("inf")
                for sid2 in by_plane[pn]:
                    d = np.linalg.norm(r_all[sid] - r_all[sid2])
                    if d < best_d:
                        best_d = d
                        best = sid2
                if best is not None:
                    edges.add(tuple(sorted((sid, best))))

    return sorted(edges)

def _plot_wrapped_edge(ax, lon1, lat1, lon2, lat2, transform, max_jump=180):
    # avoid ugly dateline wrap: skip edges that jump too far in longitude
    if abs(lon1 - lon2) > max_jump:
        return
    ax.plot([lon1, lon2], [lat1, lat2], transform=transform, linewidth=0.6, alpha=0.35)

def find_sid(shell, plane_idx=0, sat_idx_in_plane=0):
    # find the sid with given (p, s)
    for (sid, p, s, raan, inc, a, n, M0) in shell["sats"]:
        if p == plane_idx and s == sat_idx_in_plane:
            return sid
    raise ValueError("Could not find that (plane_idx, sat_idx_in_plane).")

def plot_10_timesteps_two_orbits(shell, inter_mode="one_per_neighbor",
                                ref_plane=0, ref_sat_in_plane=0,
                                n_steps=10, figsize=(14,7)):
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature

    T_orbit = 2*np.pi / shell["n"]
    times = np.linspace(0, 2*T_orbit, n_steps)

    ref_sid = find_sid(shell, ref_plane, ref_sat_in_plane)
    print(f"Reference satellite: plane={ref_plane}, s={ref_sat_in_plane}, sid={ref_sid}")
    print(f"Timespan: 0 to {2*T_orbit:.1f}s (~2 orbits), steps={n_steps}")

    for k, t in enumerate(times):
        r_all = sat_positions_ecef(shell, float(t))
        lat, lon = ecef_to_latlon(r_all)

        edges = build_links_one_timestep(shell, float(t), inter_mode=inter_mode)

        fig = plt.figure(figsize=figsize)
        ax = plt.axes(projection=ccrs.PlateCarree())
        ax.set_global()

        ax.add_feature(cfeature.OCEAN, alpha=0.35)
        ax.add_feature(cfeature.LAND, alpha=0.6)
        ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

        # draw links
        for i, j in edges:
            _plot_wrapped_edge(
                ax,
                float(lon[i]), float(lat[i]),
                float(lon[j]), float(lat[j]),
                transform=ccrs.Geodetic()
            )

        # draw satellites
        ax.scatter(lon, lat, s=6, transform=ccrs.PlateCarree(), alpha=0.85)

        # highlight reference sat (different color + bigger marker)
        ax.scatter([lon[ref_sid]], [lat[ref_sid]],
                   s=60, transform=ccrs.PlateCarree(),
                   c="red", edgecolors="black", linewidths=0.6, zorder=5)

        ax.set_title(f"Step {k+1}/{n_steps} | t={t:.0f}s (orbit={t/T_orbit:.2f}) | inter={inter_mode}")
        plt.show()
        plt.close(fig)

# Run it:
plot_10_timesteps_two_orbits(
    shell,
    inter_mode="one_per_neighbor",  # or "one_total"
    ref_plane=0,
    ref_sat_in_plane=0,
    n_steps=10
)

import numpy as np

def analyze_link_changes(shell, inter_mode="one_per_neighbor",
                         n_steps=10, n_orbits=2):
    # times used before: n_steps over 0..2 orbits
    T_orbit = 2*np.pi / shell["n"]
    times = np.linspace(0, n_orbits*T_orbit, n_steps)

    # compute edge sets
    edge_sets = []
    for t in times:
        edges = build_links_one_timestep(shell, float(t), inter_mode=inter_mode)
        edge_sets.append(set(edges))

    # per-step stats
    per_step_m = [len(es) for es in edge_sets]

    stayed_per_transition = []
    new_per_transition = []
    dropped_per_transition = []

    for k in range(len(edge_sets) - 1):
        E0 = edge_sets[k]
        E1 = edge_sets[k+1]
        stayed = E0 & E1
        new = E1 - E0
        dropped = E0 - E1

        stayed_per_transition.append(len(stayed))
        new_per_transition.append(len(new))
        dropped_per_transition.append(len(dropped))

    # totals across all transitions (note: a link can be counted multiple times across transitions)
    total_stayed = sum(stayed_per_transition)
    total_new = sum(new_per_transition)
    total_dropped = sum(dropped_per_transition)

    # stability across the whole run
    stable_all_steps = set.intersection(*edge_sets) if edge_sets else set()
    ever_seen = set.union(*edge_sets) if edge_sets else set()

    print("=== Link change analysis ===")
    print(f"Steps: {n_steps} over {n_orbits} orbits (0..{n_orbits*T_orbit:.1f}s)")
    print(f"Inter-plane mode: {inter_mode}")
    print(f"Edges per step: min={min(per_step_m)}, max={max(per_step_m)}, avg={np.mean(per_step_m):.2f}")
    print()
    print("Per-transition (t_k -> t_{k+1}) totals:")
    print(f"  Stayed (intersection) total: {total_stayed}")
    print(f"  New (appeared) total:        {total_new}")
    print(f"  Dropped (disappeared) total: {total_dropped}")
    print()
    print("Whole-run stability:")
    print(f"  Links present in ALL steps:  {len(stable_all_steps)}")
    print(f"  Unique links EVER seen:      {len(ever_seen)}")
    print()

    # Return details if you want to inspect/plot later
    return {
        "times": times,
        "edges_per_step": per_step_m,
        "stayed_per_transition": stayed_per_transition,
        "new_per_transition": new_per_transition,
        "dropped_per_transition": dropped_per_transition,
        "stable_all_steps": stable_all_steps,
        "ever_seen": ever_seen,
        "edge_sets": edge_sets,
    }

# Run it (match what you used in plotting)
stats = analyze_link_changes(shell, inter_mode="one_per_neighbor", n_steps=10, n_orbits=2)

import numpy as np
import matplotlib.pyplot as plt

# --- Vectorized Shannon capacity (works on arrays) ---
C_LIGHT = 299792458.0
K_BOLTZ = 1.380649e-23

def shannon_capacity_bps_vec(d_km, f_hz, B_hz,
                             Pt_dBW=10.0, Gt_dBi=35.0, Gr_dBi=25.0,
                             NF_dB=3.0, T_K=290.0, other_losses_dB=2.0):
    d_m = np.maximum(d_km, 1e-9) * 1000.0
    lam = C_LIGHT / f_hz
    L_fs = 20*np.log10(4*np.pi*d_m/lam)
    Pr_dBW = Pt_dBW + Gt_dBi + Gr_dBi - L_fs - other_losses_dB

    N_W = K_BOLTZ * T_K * B_hz
    N_dBW = 10*np.log10(N_W) + NF_dB

    snr_dB = Pr_dBW - N_dBW
    snr_lin = 10**(snr_dB/10.0)
    return B_hz * np.log2(1.0 + snr_lin)

def latlon_to_ecef_km(lat_deg, lon_deg, R_km=6378.137):
    lat = np.deg2rad(lat_deg)
    lon = np.deg2rad(lon_deg)
    x = R_km*np.cos(lat)*np.cos(lon)
    y = R_km*np.cos(lat)*np.sin(lon)
    z = R_km*np.sin(lat)
    return np.stack([x,y,z], axis=-1)

def _plot_wrapped_edge(ax, lon1, lat1, lon2, lat2, transform, max_jump=180):
    if abs(lon1 - lon2) > max_jump:
        return
    ax.plot([lon1, lon2], [lat1, lat2], transform=transform, linewidth=0.6, alpha=0.35)

def plot_snapshot(shell, t_sec, edges, ref_sid=None, figsize=(14,7)):
    import cartopy.crs as ccrs
    import cartopy.feature as cfeature

    r = sat_positions_ecef(shell, float(t_sec))
    lat, lon = ecef_to_latlon(r)

    fig = plt.figure(figsize=figsize)
    ax = plt.axes(projection=ccrs.PlateCarree())
    ax.set_global()
    ax.add_feature(cfeature.OCEAN, alpha=0.35)
    ax.add_feature(cfeature.LAND, alpha=0.6)
    ax.add_feature(cfeature.COASTLINE, linewidth=0.8)

    for i, j in edges:
        _plot_wrapped_edge(ax, float(lon[i]), float(lat[i]),
                           float(lon[j]), float(lat[j]),
                           transform=ccrs.Geodetic())

    ax.scatter(lon, lat, s=6, transform=ccrs.PlateCarree(), alpha=0.85)

    if ref_sid is not None:
        ax.scatter([lon[ref_sid]], [lat[ref_sid]], s=70,
                   transform=ccrs.PlateCarree(), c="red",
                   edgecolors="black", linewidths=0.6, zorder=5)

    ax.set_title(f"Satellites + ISL links @ t={t_sec:.0f}s")
    plt.show()
    plt.close(fig)

def run_10_steps_hourly_topk(shell, grids,
                            K=5,
                            inter_mode="one_per_neighbor",   # both neighbor planes
                            e_min_deg=10.0,
                            gsl_params=None,
                            isl_params=None,
                            ref_sid=0,
                            do_plots=True,
                            grid_chunk=256):
    """
    For each of 10 time steps (1 hour apart):
      - positions
      - ISL edges (in-plane +/-1 + closest in BOTH neighbor planes)
      - ISL capacities
      - For EACH grid: top-K visible satellites by GSL capacity (and those capacities)
    """

    if gsl_params is None:
        gsl_params = dict(f_hz=20e9, B_hz=250e6, Pt_dBW=10, Gt_dBi=35, Gr_dBi=25, NF_dB=3, other_losses_dB=2)
    if isl_params is None:
        isl_params = dict(f_hz=26e9, B_hz=1e9, Pt_dBW=10, Gt_dBi=30, Gr_dBi=30, NF_dB=3, other_losses_dB=2)

    # Precompute grid ECEF + normals
    grid_lat = grids["lat_c"].to_numpy()
    grid_lon = grids["lon_c"].to_numpy()
    grid_ids = grids["grid_id"].to_numpy()

    r_grids = latlon_to_ecef_km(grid_lat, grid_lon)              # (G,3)
    n_grids = r_grids / np.linalg.norm(r_grids, axis=1, keepdims=True)

    times = np.arange(0, 10*3600, 3600)  # 10 steps, 1 hour apart
    e_min_rad = np.deg2rad(e_min_deg)

    snapshots = []

    for step, t_sec in enumerate(times):
        # 1) sat positions
        r_sats = sat_positions_ecef(shell, float(t_sec))   # (N,3)
        N = r_sats.shape[0]
        G = r_grids.shape[0]

        # 2) ISL edges (your previous function)
        edges = build_links_one_timestep(shell, float(t_sec), inter_mode=inter_mode)

        # 3) ISL capacities
        isl_caps = {}
        for (i, j) in edges:
            d_km = float(np.linalg.norm(r_sats[i] - r_sats[j]))
            isl_caps[(i, j)] = float(shannon_capacity_bps_vec(d_km, **isl_params))

        # 4) For EACH grid: choose top-K visible satellites by GSL capacity
        grid_topk = {}  # grid_id -> list[(sat_id, cap_bps)] sorted high->low

        # chunk grids to avoid huge (G,N,3) allocations
        for start in range(0, G, grid_chunk):
            end = min(G, start + grid_chunk)
            rg = r_grids[start:end]          # (Gc,3)
            ng = n_grids[start:end]          # (Gc,3)
            gids = grid_ids[start:end]
            Gc = end - start

            # rho[g,s,:] = r_sats[s,:] - r_grid[g,:]
            rho = r_sats[None, :, :] - rg[:, None, :]             # (Gc,N,3)
            rho_norm = np.linalg.norm(rho, axis=2)                # (Gc,N)
            num = np.sum(rho * ng[:, None, :], axis=2)            # (Gc,N)
            elev = np.arcsin(np.clip(num / rho_norm, -1.0, 1.0))  # (Gc,N)

            vis = elev >= e_min_rad

            # capacity for all pairs in chunk, then mask
            caps = shannon_capacity_bps_vec(rho_norm, **gsl_params)
            caps[~vis] = -np.inf

            for ii in range(Gc):
                row = caps[ii]
                valid = np.isfinite(row)
                nv = int(valid.sum())
                if nv == 0:
                    continue

                if nv <= K:
                    idx = np.where(valid)[0]
                    idx = idx[np.argsort(row[idx])[::-1]]
                else:
                    idx = np.argpartition(row, -K)[-K:]
                    idx = idx[np.argsort(row[idx])[::-1]]

                grid_topk[int(gids[ii])] = [(int(sid), float(row[sid])) for sid in idx]

        if do_plots:
            plot_snapshot(shell, float(t_sec), edges, ref_sid=ref_sid)

        # quick summary
        total_gsl_links = sum(len(v) for v in grid_topk.values())
        avg_isl = (np.mean(list(isl_caps.values()))/1e9) if isl_caps else 0.0
        print(f"[{step+1}/10] t={t_sec:>5.0f}s | ISL edges={len(edges)} | avg ISL cap={avg_isl:.2f} Gbps | "
              f"grids w/ >=1 sat={len(grid_topk)} | total GSL links(top{K})={total_gsl_links}")

        snapshots.append({
            "t_sec": float(t_sec),
            "edges": edges,
            "isl_caps": isl_caps,     # (i,j) -> bps
            "grid_topk": grid_topk,   # grid_id -> [(sat_id, cap_bps), ...] length<=K
        })

    return snapshots

# Run:
snapshots = run_10_steps_hourly_topk(
    shell, grids,
    K=1,
    inter_mode="one_per_neighbor",  # both neighbor planes
    e_min_deg=10.0,
    ref_sid=0,
    do_plots=True,
    grid_chunk=256
)

import os
import numpy as np
import pandas as pd

# =============== (A) Ensure grids have population ===============
def add_population_from_worldpop_if_missing(grids, pop_tif, grid_res_deg=5.0):
    """
    If grids already has a 'population' column, does nothing.
    Otherwise: aggregates WorldPop raster into your existing grid centers (lat_c, lon_c).
    This matches the typical approach in your notebook.

    Requires: rasterio
    """
    if "population" in grids.columns:
        return grids

    import rasterio
    from rasterio.windows import Window

    g = grids.copy()

    # Build grid cell boundaries from centers (assumes regular grid spacing)
    half = grid_res_deg / 2.0
    # for each grid center, define bounding box [lat-half, lat+half] x [lon-half, lon+half]
    # We'll sample raster by converting bounds to pixel windows.

    with rasterio.open(pop_tif) as src:
        pop = src.read(1, masked=True)
        transform = src.transform

        def lonlat_to_rowcol(lon, lat):
            col, row = ~transform * (lon, lat)
            return int(np.floor(row)), int(np.floor(col))

        pops = []
        for lat_c, lon_c in zip(g["lat_c"].to_numpy(), g["lon_c"].to_numpy()):
            lat_min, lat_max = lat_c - half, lat_c + half
            lon_min, lon_max = lon_c - half, lon_c + half

            # Raster rows typically go from top (lat max) to bottom (lat min)
            r1, c1 = lonlat_to_rowcol(lon_min, lat_max)
            r2, c2 = lonlat_to_rowcol(lon_max, lat_min)

            rmin, rmax = sorted((r1, r2))
            cmin, cmax = sorted((c1, c2))

            # clip to raster bounds
            rmin = max(rmin, 0); cmin = max(cmin, 0)
            rmax = min(rmax, pop.shape[0]-1); cmax = min(cmax, pop.shape[1]-1)

            if rmin > rmax or cmin > cmax:
                pops.append(0.0)
                continue

            window = Window.from_slices((rmin, rmax+1), (cmin, cmax+1))
            block = src.read(1, window=window, masked=True)
            pops.append(float(block.filled(0).sum()))

    g["population"] = pops
    return g


# =============== (B) Build node tables ===============
def export_nodes(grids, shell, out_dir):
    os.makedirs(out_dir, exist_ok=True)

    # Prefix IDs to avoid collisions (grid_id might overlap sat_id)
    grids_nodes = pd.DataFrame({
        "node_id": ["G_" + str(x) for x in grids["grid_id"].tolist()],
        "type": "G",
        "grid_id": grids["grid_id"].astype(int),
        "lat": grids["lat_c"].astype(float),
        "lon": grids["lon_c"].astype(float),
        "population": grids["population"].astype(float) if "population" in grids.columns else np.nan,
    })

    sats = shell["sats"]  # (sid, p, s, raan, inc, a, n, M0)
    sat_nodes = pd.DataFrame([{
        "node_id": f"S_{sid}",
        "type": "S",
        "sat_id": int(sid),
        "plane": int(p),
        "sat_in_plane": int(s),
        "raan": float(raan),
        "inc": float(inc),
        "a_km": float(a),
        "n": float(n),
        "M0": float(M0),
    } for (sid, p, s, raan, inc, a, n, M0) in sats])

    grids_nodes.to_csv(os.path.join(out_dir, "nodes_grids.csv"), index=False)
    sat_nodes.to_csv(os.path.join(out_dir, "nodes_sats.csv"), index=False)

    return grids_nodes, sat_nodes


# =============== (C) Export satellite states per timestep ===============
def export_sat_states(shell, times_sec, out_dir):
    os.makedirs(out_dir, exist_ok=True)

    rows = []
    for t in times_sec:
        r = sat_positions_ecef(shell, float(t))     # (N,3) km
        lat, lon = ecef_to_latlon(r)                # (N,), (N,)
        for sid in range(r.shape[0]):
            rows.append({
                "t_sec": float(t),
                "node_id": f"S_{sid}",
                "sat_id": int(sid),
                "x_km": float(r[sid,0]),
                "y_km": float(r[sid,1]),
                "z_km": float(r[sid,2]),
                "lat": float(lat[sid]),
                "lon": float(lon[sid]),
            })

    df = pd.DataFrame(rows)
    df.to_csv(os.path.join(out_dir, "sat_states.csv"), index=False)
    return df


# =============== (D) Convert per-step edges to time intervals ===============
def edges_stepdict_from_snapshots(snapshots, topk_only=True):
    """
    Returns:
      times: sorted times (seconds)
      step_edges: list of dict { (src_node_id, dst_node_id, edge_type) : cap_bps } per step
    """
    times = [float(s["t_sec"]) for s in snapshots]
    step_edges = []

    for s in snapshots:
        E = {}

        # ISL edges from isl_caps: keys (i,j) already undirected with i<j
        for (i, j), cap in s["isl_caps"].items():
            key = (f"S_{i}", f"S_{j}", "ISL")
            E[key] = float(cap)

        # GSL edges from grid_topk: grid_id -> [(sat_id, cap_bps), ...]
        for gid, lst in s["grid_topk"].items():
            for (sid, cap) in lst:
                key = (f"G_{gid}", f"S_{sid}", "GSL")
                E[key] = float(cap)

        step_edges.append(E)

    return times, step_edges


def merge_edge_intervals(times, step_edges, step_duration_sec):
    """
    Merges consecutive steps where the same edge exists.
    Output rows have:
      src, dst, type, start_sec, end_sec, cap_mean, cap_min, cap_max, samples
    """
    active = {}  # key -> dict(start, last_t, caps[])
    intervals = []

    for idx, t in enumerate(times):
        cur = step_edges[idx]

        # Start/continue edges present now
        for key, cap in cur.items():
            if key in active:
                active[key]["last_t"] = t
                active[key]["caps"].append(cap)
            else:
                active[key] = {"start": t, "last_t": t, "caps": [cap]}

        # End edges not present now (compare against current set)
        cur_keys = set(cur.keys())
        for key in list(active.keys()):
            if key not in cur_keys:
                st = active[key]["start"]
                end = active[key]["last_t"] + step_duration_sec
                caps = np.array(active[key]["caps"], dtype=float)
                src, dst, etype = key
                intervals.append({
                    "src": src,
                    "dst": dst,
                    "type": etype,
                    "start_sec": float(st),
                    "end_sec": float(end),
                    "cap_mean_bps": float(caps.mean()),
                    "cap_min_bps": float(caps.min()),
                    "cap_max_bps": float(caps.max()),
                    "samples": int(len(caps)),
                })
                del active[key]

    # Close remaining active edges
    for key, info in active.items():
        st = info["start"]
        end = info["last_t"] + step_duration_sec
        caps = np.array(info["caps"], dtype=float)
        src, dst, etype = key
        intervals.append({
            "src": src,
            "dst": dst,
            "type": etype,
            "start_sec": float(st),
            "end_sec": float(end),
            "cap_mean_bps": float(caps.mean()),
            "cap_min_bps": float(caps.min()),
            "cap_max_bps": float(caps.max()),
            "samples": int(len(caps)),
        })

    return pd.DataFrame(intervals)


def export_dynamic_graph(snapshots, out_dir, step_duration_sec=3600):
    os.makedirs(out_dir, exist_ok=True)

    times, step_edges = edges_stepdict_from_snapshots(snapshots)
    intervals_df = merge_edge_intervals(times, step_edges, step_duration_sec)

    # Save both: per-step edges (optional) and merged intervals
    intervals_df.to_csv(os.path.join(out_dir, "edges_intervals.csv"), index=False)

    # Also save per-step edges as long-form (handy for debugging)
    rows = []
    for t, E in zip(times, step_edges):
        for (src, dst, etype), cap in E.items():
            rows.append({"t_sec": float(t), "src": src, "dst": dst, "type": etype, "cap_bps": float(cap)})
    step_df = pd.DataFrame(rows)
    step_df.to_csv(os.path.join(out_dir, "edges_per_step.csv"), index=False)

    return intervals_df, step_df


# ===================== RUN EVERYTHING =====================
out_dir = "/content/drive/MyDrive/sat_sim_project/export_graph"
pop_tif = "/content/drive/MyDrive/sat_sim_project/worldpop_ppp_2020_1km.tif"

# 1) Make sure grids has population
grids2 = add_population_from_worldpop_if_missing(grids, pop_tif, grid_res_deg=5.0)

# 2) Export nodes
export_nodes(grids2, shell, out_dir)

# 3) Export satellite states for the same times as snapshots
times_sec = [float(s["t_sec"]) for s in snapshots]
export_sat_states(shell, times_sec, out_dir)

# 4) Export dynamic edges (intervals + per-step)
intervals_df, step_df = export_dynamic_graph(snapshots, out_dir, step_duration_sec=3600)

print("Saved to:", out_dir)
print("Intervals rows:", len(intervals_df), "| Per-step rows:", len(step_df))